#This program makes the computer pick a random number. So, the user is given as many chances to guess this number.
#The program ends with a message once the user guesses the number correctly.
#This number can also be programmed such as the roles are reversed.
#That is, the user picks a random number, and the computer tries to guess the number.
#The computer asks for prompts from the user, whether the current guessed number is higher, lower or equal to the no.
#picked by the user for the computer to guess.

import random                           #importing the random class, which helps in generating a random no.

x = int(input("Enter the max. limit"))  #Getting the max limit for the computer to pick a number.
random_number = random.randint(1,x)     #A random no. is generated by the computer withing 1 and x.
print(f"I'm ready with a number. Now Guess the number between 1 and {x}: ")
counter = 1                             #counter variable is used to keep count of the no. of tries taken by the user to guess the correct no.
n=0                                     #initializing n, which will store the number guessed by the user in each try.
while(True):                            
    print(f"Try {counter}:"+" ")        #displaying the number of the try.
    counter += 1                        #incrementing counter variable
    n = int(input())                    #getting the guess from the user for the nth try.
    if(n == random_number):             #checking whether the guessed no. is equal to the no. picked by the computer.
        print("Congrats!! The no. you guessed is correct."+'\n'+f"You guessed the no. after {counter-1} tries.")
        break                           #Exiting the loop once the user guesses the no. correctly.
    elif(n>random_number):              #msg to display if the guess is greater than the correct no.
        print("The no. you guessed is higher. Please try a smaller no.")
    else:                               #msg to display if the guess is lesser than the correct no.
        print("The no. you guessed is little low. Please try a larger no.")
